# Generated by Django 5.2.8 on 2025-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('self_help', 'Self-Help'), ('romance', 'Romance'), ('trading_finance', 'Trading & Finance'), ('hindi', 'Hindi Books'), ('kids', 'Kids Books'), ('manga', 'Manga'), ('mythology', 'Mythology'), ('science', 'Science'), ('biography', 'Biography & Autobiography')], default='self_help', max_length=50),
        ),
    ]
