# Generated by Django 5.2.8 on 2025-12-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('new_arrivals', 'NEW ARRIVALS'), ('manga_comics', 'MANGA & COMICS'), ('most_read_combos', 'MOST READ COMBOS'), ('self_improvements', 'SELF IMPROVEMENTS'), ('romance', 'ROMANCE ON SALE'), ('hindi', 'HINDI BOOKS'), ('business_stock_market', 'BUSINESS & STOCK-MARKET'), ('mega_combo', 'MEGA COMBO')], default='self_help', max_length=50),
        ),
    ]
