# Generated by Django 5.2.8 on 2025-12-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0005_remove_product_author_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variety',
            name='type',
            field=models.CharField(choices=[('NEW', 'NEW ARRIVAL'), ('MNG', 'MANGA & COMICS'), ('MRC', 'MOST READ COMBOS'), ('SFI', 'SELF IMPROVEMENTS'), ('ROS', 'ROMANCE ON SALE'), ('HIN', 'HINDI BOOKS'), ('BSM', 'BUSINESS & STOCK-MARKET'), ('MGC', 'MEGA COMBO')], max_length=4, unique=True),
        ),
    ]
