# Generated by Django 5.2.8 on 2025-11-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebook',
            name='category',
            field=models.CharField(choices=[('sale', 'Self-Help (On Sale)'), ('romance', 'Romance'), ('trading', 'Trading & Finance'), ('manga', 'Manga')], default='sale', max_length=20),
        ),
    ]
