# Generated by Django 5.2.8 on 2025-12-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_order_payment_status_order_txn_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='txn_id',
        ),
    ]
